// <auto-generated />
using AlfTekPro.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AlfTekPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260306000011_AddEmployeeDocuments")]
    partial class AddEmployeeDocuments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
